/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ykvtgjzfxszbtenueaob"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdnRnanpmeHN6YnRlbnVlYW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODI5NjgsImV4cCI6MjA3MjQ1ODk2OH0.sP4YX-6wlDN4qW9xa_Hon-m3LME7JIviCrf6Jmap4zI"